### ISSUE TITLE
小程序问题

### ISSUE THREAD

**Issue by ethan-phu** [jas0ncn/szushudong#1]
![Uploading QQ图片20170505134159.png…]()

**Comment by ethan-phu** [comment]
WAService.js:7 Uncaught TypeError: Cannot set property 'Promise' of undefined(anonymous function) @ index.js [sm]:4require @ WAService.js:7(anonymous function) @ WAService.js:7(anonymous function) @ app.js [sm]:3require @ WAService.js:7(anonymous function) @ app.js:66
WAService.js:7 Uncaught ReferenceError: regeneratorRuntime is not defined(anonymous function) @ request.js [sm]:2(anonymous function) @ request.js:106require @ WAService.js:7(anonymous function) @ WAService.js:7(anonymous function) @ index.js [sm]:6require @ WAService.js:7(anonymous function) @ index.js:325
appservice:17 Fri May 05 2017 13:40:13 GMT+0800 (中国标准时间) page 编译错误
appservice:18  pages/index 出现脚本错误或者未正确调用 Page()(anonymous function) @ appservice:18
WAService.js:7 Uncaught ReferenceError: regeneratorRuntime is not defined(anonymous function) @ request.js [sm]:2(anonymous function) @ request.js:106require @ WAService.js:7(anonymous function) @ WAService.js:7(anonymous function) @ new.js [sm]:4require @ WAService.js:7(anonymous function) @ new.js:535
appservice:23 Fri May 05 2017 13:40:13 GMT+0800 (中国标准时间) page 编译错误
appservice:24  pages/new 出现脚本错误或者未正确调用 Page()(anonymous function) @ appservice:24
WAService.js:7 Uncaught ReferenceError: regeneratorRuntime is not defined(anonymous function) @ request.js [sm]:2(anonymous function) @ request.js:106require @ WAService.js:7(anonymous function) @ WAService.js:7(anonymous function) @ detail.js [sm]:4require @ WAService.js:7(anonymous function) @ detail.js:713
appservice:29 Fri May 05 2017 13:40:13 GMT+0800 (中国标准时间) page 编译错误
appservice:30  pages/detail 出现脚本错误或者未正确调用 Page()(anonymous function) @ appservice:30
WAService.js:6 Fri May 05 2017 13:40:16 GMT+0800 (中国标准时间) Page route 错误

**Comment by ethan-phu** [comment]
这是我的错误。为什么会这样呢？求解决下

**Comment by ethan-phu** [comment]
还有你封装好发送到后台，后台的req，数据放在哪里。我body里没有params,query里也没有

**Comment by jas0ncn** [comment]
用调试工具的时候，要把小程序的目录选择为dist那个目录

请求只是对 session token 进行了封装，其他的都是在调用的时候放进去的。因为每个接口所要的数据不一样

**Comment by ethan-phu** [comment]
还有一个问题。就是图片上传那个。wepy.uploadFile,我在nodejs后台怎么拿到数据呀？一直不明白。

**Comment by jas0ncn** [comment]
后端其实就是普通的文件上传而已。。和普通的ajax是完全一样的。。

**Comment by ethan-phu** [comment]
嗯嗯。明白了。嘿嘿
