### ISSUE TITLE
wepy build --watch 时报错

### ISSUE THREAD

**Issue by jiangdi0924** [jas0ncn/szushudong#10]
`/Users/norton/HomesteadSyncDir/szushudong/src/components/clist.wpy
  221:20  error  Redundant Boolean call  no-extra-boolean-cast

✖ 1 problem (1 error, 0 warnings)

[11:51:24] [编译] 页面: src/pages/detail.wpy

/Users/norton/HomesteadSyncDir/szushudong/src/pages/detail.wpy
  452:20  error  Redundant Boolean call  no-extra-boolean-cast

✖ 1 problem (1 error, 0 warnings)`

**Comment by jas0ncn** [comment]
这个是 eslint 报的错误，你自己查询一下 no-extra-boolean-cast，按规则加上就行。
