### ISSUE TITLE
学习交流

### ISSUE THREAD

**Issue by jessjava** [jas0ncn/szushudong#11]
你好，能否给一个 key 访问您的 API？学习用。谢谢哦

我的微信访问
https://sd.iszu.cn/user/wxlogin
结果是这样的。能帮忙一下吗。
data
:
{}
errcode
:
11
errmsg
:
"ERR_SESSION_KEY_EXCHANGE_FAILED"

**Comment by jas0ncn** [comment]
https://github.com/jas0ncn/szushudong/blob/master/api-doc.md
