### ISSUE TITLE
下载源码后在微信开发助手里打不开，所有文件夹都试过了，一直提示使用空白目录创建项目

### ISSUE THREAD

**Issue by yarkable** [jas0ncn/szushudong#12]

**Comment by jas0ncn** [comment]
https://github.com/jas0ncn/szushudong#%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E8%BF%90%E8%A1%8C
好好看 readme，先用 wepy 运行，再选择 dist 目录
