### ISSUE TITLE
请问该项目没有开源后没有前端页面吗？提示未找到 app.json 中的定义的 pages "pages/index" 对应的 JS 文件

### ISSUE THREAD

**Issue by Whales233** [jas0ncn/szushudong#16]
提示未找到 app.json 中的定义的 pages "pages/index" 对应的 JS 文件
http://ww1.sinaimg.cn/large/e51d798egy1fsk5w5njrgj20ts0fpgo5.jpg

**Comment by jas0ncn** [comment]
> - `es6`: 对应关闭ES6转ES5选项，关闭。 重要：未关闭会运行报错。
> - `postcss`: 对应关闭上传代码时样式自动补全选项，关闭。 重要：某些情况下漏掉此项也会运行报错。
> - `minified`: 对应关闭代码压缩上传选项，关闭。重要：开启后，会导致真机 computed, props.sync 等等属性失效。（注：压缩功能可使用 WePY 提供的 build 指令代替，详见后文相关介绍以及 Demo 项目根目录中的wepy.config.js和package.json文件。）
> - `urlCheck`: 对应不检查安全域名选项，开启。 如果已配置好安全域名则建议关闭。

https://tencent.github.io/wepy/document.html
