### ISSUE TITLE
未找到 app.json 中的定义的 pages "pages/index" 对应的 JS 文件

### ISSUE THREAD

**Issue by Whales233** [jas0ncn/szushudong#17]
请问出现这种情况是对应的wpy文件中js文件没有编译出来吗？
新人小白，求解。

**Comment by Whales233** [comment]
http://ww1.sinaimg.cn/large/e51d798egy1fsmcagrkjwj20ts0fpgo5.jpg

**Comment by jas0ncn** [comment]
https://tencent.github.io/wepy/document.html#/?id=%E6%B7%BB%E5%8A%A0%E9%A1%B9%E7%9B%AE
