### ISSUE TITLE
接口报错了

### ISSUE THREAD

**Issue by kainy** [jas0ncn/szushudong#2]
用开发者工具打开后，不断发请求，但是接口都返回错误：

> Request URL:https://sd.iszu.cn/v2/notifications
Request Method:GET
Status Code:401 

麻烦看看是否服务端有问题。

**Comment by jas0ncn** [comment]
因为请求 `/wxlogin` 的登录失败了，所以其他的 api 都会返回 401 无权限。
后端的具体 api 和请求返回的数据，我这几天会整理出一个文档，需要自己 mock 或者实现。
因为小程序的 appid 不一样，所以微信登录的时候就会失败。。

**Comment by aben1188** [comment]
“后端的具体 api 和请求返回的数据，我这几天会整理出一个文档”，请问这个文档能提供一份参考吗？如果能同时提供一份MySQL数据库Schema将不胜感激！谢谢！
