### ISSUE TITLE
请问project.config.json这个文件是直接修改值为false么，小程序无法正确运行

### ISSUE THREAD

**Issue by xiaomizhou66** [jas0ncn/szushudong#20]
F:\qianduan_dir\00program\wechat\szushudong-master\src\components\clist.wpy
  151:9   error  Unexpected console statement  no-console
  202:9   error  Unexpected console statement  no-console
  221:20  error  Redundant Boolean call        no-extra-boolean-cast

✖ 3 problems (3 errors, 0 warnings)

[22:56:20] [编译] 页面: src\pages\detail.wpy

F:\qianduan_dir\00program\wechat\szushudong-master\src\pages\detail.wpy
  210:9   error  Unexpected console statement     no-console
  250:19  error  Empty block statement            no-empty
  275:7   error  Unexpected console statement     no-console
  292:19  error  Empty block statement            no-empty
  312:30  error  'idx' is defined but never used  no-unused-vars
  452:20  error  Redundant Boolean call           no-extra-boolean-cast

✖ 6 problems (6 errors, 0 warnings)

**Comment by jas0ncn** [comment]
这个应该是 eslint 报错了吧。。 project.config.json 是自动生成的
