### ISSUE TITLE
Async/Await Q

### ISSUE THREAD

**Issue by jessjava** [jas0ncn/szushudong#4]
我在用 wepy 框架开发小程序时，wpy 文件中使用await 编译后页面运行报错。出现脚本错误或者未正确调用 Page(),  应该是不识别，怎么配置支持 await 写法呢？

**Comment by jas0ncn** [comment]
关闭开发者工具中 ES6 转 ES5 的功能。
另外要使用 await 本身这个函数需要是 async 的。

例如：
```javascript
async function () {
   await xxx()
}
```

如下写法是错误的：
```javascript
function () {
   await xxx()
}
```
