### ISSUE TITLE
点击树洞的评论按钮，会跳进去两个页面，一个是空白页，退出也是，已测试深大的树洞也会

### ISSUE THREAD

**Issue by NullYing** [jas0ncn/szushudong#9]
![image](https://user-images.githubusercontent.com/10618381/29108503-d6667cba-7d11-11e7-9e0c-0393b0c23b1c.png)
调试发现会调用两次onLoad

**Comment by NullYing** [comment]
知道原因了，嵌套navigator导致的

**Comment by jas0ncn** [comment]
我也发现了，感觉是微信的 bug，你可以把原来嵌套的 navigator 改成并行的。
